### PR TITLE
Fix NOT_COORDINATOR warnings for Kafka consumer offset commit requests

### LINKED ISSUE #1687: Kafka consumers through shotover frequently seeing NOT_COORDINATOR warnings
When consuming from multi-partition topics through Shotover, consumers are frequently showing warnings logs like these:

```
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
```

The consumers are able to consume the messages eventually, but this seems to be causing the clients to frequently disconnect and reconnect. See this log sample for example, which shows messages being consumed in between bouts of disconnects:

```
topic = test, partition = 4, offset = 5, key = my-key, value = my-value
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
topic = test, partition = 4, offset = 6, key = my-key, value = my-value
topic = test, partition = 4, offset = 7, key = my-key, value = my-value
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
topic = test, partition = 4, offset = 8, key = my-key, value = my-value
topic = test, partition = 4, offset = 9, key = my-key, value = my-value
topic = test, partition = 4, offset = 10, key = my-key, value = my-value
topic = test, partition = 4, offset = 11, key = my-key, value = my-value
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: coordinator unavailable. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Discovered group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Offset commit failed on partition test-2 at offset 0: This is not the correct coordinator.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Group coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null) is unavailable or invalid due to cause: error response NOT_COORDINATOR. isDisconnected: false. Rediscovery will be attempted.
[main] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-my-group-1, groupId=my-group] Requesting disconnect from last known coordinator rack2.paris-kafka-psc-test.instaclustr.com:9091 (id: 2147483645 rack: null)
[main] INFO org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-my-group-1, groupId=my-group] Client requested disconnect from node 2147483645
```

This has been observed with the Java and Confluent Kafka C# consumers so far.

While these consumers were running, the shotover_out_of_rack_requests_count metric was steadily increasing (by at least 1 per second), which I suspect could be related.

### PR DESCRIPTION
**Pull request by justinweng-instaclustr**
This PR fixes the `NOT_COORDINATOR` warning when Kafka consumers try to commit offsets. It's fixed by routing the `OffsetCommit` requests to the group coordinator in the KafkaSinkCluster method `route_requests()`.

It also adds a new Kafka integration test case `produce_consume_commit_offsets_partitions1` which calls `commit_sync(&offsets)` to commit the offset after a valid consume, and calls `committed` to verify the offset has been successfully committed (refs: [Kafka Java driver commitSync()](https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitSync--:~:text=commitSync(Map)-,commitSync,-public%C2%A0void%C2%A0commitSync), [Kafka Java driver committed()](https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitSync--:~:text=committed(TopicPartition%2C%20Duration)-,committed,-public%C2%A0Map), [Kafka C++ driver commit()](https://docs.rs/rdkafka/latest/rdkafka/consumer/trait.Consumer.html#tymethod.commit), [Kafka C++ driver committed_offsets()](https://docs.rs/rdkafka/latest/rdkafka/consumer/trait.Consumer.html#tymethod.committed_offsets)).

[`commit_sync`](https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitSync--:~:text=commitSync(Map)-,commitSync,-public%C2%A0void%C2%A0commitSync) was chosen over [`commit_async`](https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitAsync-org.apache.kafka.clients.consumer.OffsetCommitCallback-:~:text=commitAsync(OffsetCommitCallback)-,commitAsync,-public%C2%A0void%C2%A0commitAsync) due to the following reasons:

- We need to check if the offset has been committed after sending the offset commit request, and hence need the `commit_sync` to block until the commit succeeds.

- It may be possible to wrap `committed()` in the [OffsetCommitCallback](https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/clients/consumer/OffsetCommitCallback.html) for the `commitAsync()` method so that the check on committed offsets can be triggered after `commitAsync()` completes. But it seems complicated to implement and probably not worth the effort.

Closes #1687

### CODE REVIEW

File: test-helpers/src/connection/kafka/java.rs [hunk 1]
```diff
@@ -189,7 +189,7 @@ pub struct KafkaConsumerJava {
     waiting_records: VecDeque<Value>,
 }
 
-impl KafkaConsumerJava {
+impl<'a> KafkaConsumerJava {
```
Comment (rukai) [inline test-helpers/src/connection/kafka/java.rs:192]: `<'a>` can be removed

File: test-helpers/src/connection/kafka/mod.rs [hunk 2]
```diff
@@ -164,6 +165,28 @@ impl KafkaConsumer {
             }
         }
     }
+
+    /// The offset to be committed should be lastProcessedMessageOffset + 1.
+    pub fn assert_commit_offsets(&self, offsets: HashMap<TopicPartition, i64>) {
+        match self {
+            #[cfg(feature = "kafka-cpp-driver-tests")]
+            Self::Cpp(cpp) => cpp.commit(&offsets, rdkafka::consumer::CommitMode::Sync),
```
Comment (rukai) [inline test-helpers/src/connection/kafka/mod.rs:173]: The KafkaConsumerCpp and KafkaConsumerJava should be implementing a common interface.
So they should both have the same method names and take the same arguments.

File: test-helpers/src/connection/kafka/mod.rs [hunk 3]
```diff
@@ -164,6 +165,28 @@ impl KafkaConsumer {
             }
         }
     }
+
+    /// The offset to be committed should be lastProcessedMessageOffset + 1.
+    pub fn assert_commit_offsets(&self, offsets: HashMap<TopicPartition, i64>) {
```
Comment (rukai) [inline test-helpers/src/connection/kafka/mod.rs:170]: I think this method should be async, if the integration tests block then shotover logs are also blocked which can make debugging tricky.
I think the best way to solve this is to call within the cpp/java consumers https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html so that we can call the blocking functions without blocking the async runtime.

For example we already do that here:
https://github.com/shotover/shotover-proxy/blob/6ec2022ff303c553fd183ffeef9204730d2c44ae/test-helpers/src/connection/kafka/java.rs#L212

File: test-helpers/src/connection/kafka/mod.rs [hunk 4]
```diff
@@ -164,6 +165,28 @@ impl KafkaConsumer {
...
+
+        let partitions = offsets.keys().cloned().collect::<HashSet<_>>();
+
+        let responses = match self {
+            #[cfg(feature = "kafka-cpp-driver-tests")]
+            Self::Cpp(cpp) => cpp.committed_offsets(partitions),
+            Self::Java(java) => java.committed(partitions),
+        };
+
+        for (topic_partition, offset) in offsets {
```
Comment (rukai) [inline test-helpers/src/connection/kafka/mod.rs:185]: Since the kafka driver will return a variable number of elements in responses, it would be good to make an assertion on the number of responses to make sure extra responses were not returned.

Would it be appropriate to assert that `assert_eq!(offsets.len(), responses.len())`?

File: test-helpers/src/connection/kafka/mod.rs (hunk 3 above)
Comment (justinweng-instaclustr) [reply test-helpers/src/connection/kafka/mod.rs:170]: Cool will change it

File: test-helpers/src/connection/kafka/cpp.rs [hunk 5]
```diff
@@ -157,6 +158,68 @@ impl KafkaConsumerCpp {
...
+            )
+            .expect("Failed to add the topic and partition");
+        }
+
+        let committed_offsets = self
+            .consumer
+            .committed_offsets(tpl, Timeout::After(Duration::from_secs(30)))
+            .unwrap();
+
+        for tp in &partitions {
```
Comment (rukai) [inline test-helpers/src/connection/kafka/cpp.rs:206]: I think this can be simplified:

image

File: test-helpers/src/connection/kafka/mod.rs (hunk 4 above)
Comment (justinweng-instaclustr) [reply test-helpers/src/connection/kafka/mod.rs:185]: yeah will add this assertion

File: shotover-proxy/tests/kafka_int_tests/test_cases.rs [hunk 6]
```diff
@@ -158,10 +169,123 @@ pub async fn produce_consume_partitions1(
...
+            .assert_consume(ExpectedResponse {
+                message: "Message2".to_owned(),
+                key: Some("Key".to_owned()),
+                topic_name: topic_name.to_owned(),
+                offset: Some(2),
+            })
+            .await;
+    }
+}
+
```
Comment (justinweng-instaclustr) [inline shotover-proxy/tests/kafka_int_tests/test_cases.rs:282]: Add another test case for consumer in "consumer_group_without_offsets" that should consume the Initial message.

**Review by rukai — APPROVED** [review]
nice work!
The extra test coverage will be really handy.
